name: Deploy Slides to GitHub Pages

on:
  push:
    branches: [main] 
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build slides
        run: npm run build

      - name: Copy examples
        run: |
          cp -r day1/lib/ dist/day1/lib/
          cp day1/example.html dist/day1/example.html
          cp day1/example.js dist/day1/example.js
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Zip examples folder
        run: |
          mkdir release
          
          mkdir starter-kit-1
          cp -r day1/lib starter-kit-1/lib
          cp day1/template.html starter-kit-1/index.html

          zip -r release/starter-kit-1.zip starter-kit-1
          tar -czf release/starter-kit-1.tar.gz starter-kit-1

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "build-${{ github.run_number }}"
          release_name: "Material zum Workshop #${{ github.run_number }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload zip
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/starter-kit-1.zip
          asset_name: starter-kit-1.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload tar.gz
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/starter-kit-1.tar.gz
          asset_name: starter-kit-1.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}